### ISSUE TITLE
Use mvvm archecture corotines and dagger 

### ISSUE THREAD

**Issue by Ittechsolutions** [CodeBoy722/MediaFacer_Kotlin#1]
please use mvvvm architecture kotlin corotines for background loading and hilt dagger

**Comment by CodeBoy722** [comment]
hello @Ittechsolutions, i am planning  dependency injection with hilt as the last thing to implement in this project, as you could have noticed my library is still under construction, secondly can you explain to me in what manner the project does not use MVVM and Couroutines, these two are implemented and work fine
