### ISSUE TITLE
Folder issue

### ISSUE THREAD

**Issue by sheikpunia1** [CodeBoy722/MediaFacer_Kotlin#2]
I have place mp3 file in notification folder. In the home screen its not coming in  the list but when i search in app in home screen it comes in the searching list

**Comment by CodeBoy722** [comment]
hello @sheikpunia1  this is an issue I have also noticed generally from android 10 and above, I am still investigating it, seems it a problem with the MediaStore not getting updated properly, as a workaround turn off your device and on again, i will swiftly update once i find an optimal  solution

**Comment by sheikpunia1** [comment]
> have also noticed generally from and

i have found solution for it. In AudioGet class empty this audioSelection and it will load all audio from the folders.

**Comment by CodeBoy722** [comment]
Ok great I will check that and see then maybe write a function to do that automatically
